folio-org/stripes-erm-components

CHANGELOG.md, lib/CreateOrganizationModal/CreateOrganizationModal.js, lib/CreateOrganizationModal/CreateOrganizationModalContainer.js, lib/CreateOrganizationModal/readme.md, lib/OrganizationSelection/OrganizationSelection.js, lib/OrganizationSelection/OrganizationSelectionContainer.js, lib/OrganizationSelection/readme.md, package.json
* Changed `OrganizationSelection` component to support `path` prop. Avail in 1.0.2.
* Changed `CreateOrganizationModal` component to support `path` prop. Avail in 1.0.2.
=> Added ability to specify path for organisations endpoint

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/pt_BR.json
=> Update translation strings as of 20190227T140407

CHANGELOG.md, index.js, lib/DocumentCard/DocumentCard.css, lib/DocumentCard/DocumentCard.js, lib/DocumentCard/index.js, lib/DocumentCard/readme.md, lib/Spinner/Spinner.js, lib/Spinner/index.js, package.json, translations/stripes-erm-components/en.json
- Added `DocumentCard`
- Added `Spinner`
=> Added DocumentCard and Spinner components

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190228T144944

lib/DocumentCard/DocumentCard.js, lib/DocumentsFieldArray/DocumentsFieldArray.js
- Added `data-test` attributes
- Added dynamic `id` generation
=> Document Components: Support for automated tests

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190306T161944

translations/stripes-erm-components/ar.json
=> Update translation strings as of 20190312T134015

CHANGELOG.md, index.js, lib/LicenseTermsList/LicenseTermsList.js, lib/LicenseTermsList/index.js, lib/LicenseTermsList/readme.md, package.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en.json, translations/stripes-erm-components/en_US.json
rebase erm-96  to master
edit CHANGELOG.md
=> Erm 96 rebased to master

translations/stripes-erm-components/en_GB.json
=> Update translation strings as of 20190416T182157

translations/stripes-erm-components/es_ES.json
=> Update translation strings as of 20190425T181703

translations/stripes-erm-components/es_ES.json
=> Update translation strings as of 20190429T154045

lib/InternalContactsFieldArray/InternalContactsFieldArray.js, lib/LicenseEndDate/LicenseEndDate.js
- Added rendering of user middle names.
- Force re-render of user names when list of users changes.
=> ERM-179: Tweak InternalContactsFieldArray render logic

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190510T130015

CHANGELOG.md, lib/LicenseTermsList/LicenseTermsList.js, lib/LicenseTermsList/tests/LicenseTermsList-test.js, lib/LicenseTermsList/tests/interactor.js, package.json
Render license term notes if they exist.
=> ERM-146: Display license term notes

lib/InternalContactsFieldArray/InternalContactsFieldArray.js, lib/OrganizationsFieldArray/OrganizationsFieldArray.js
Names and roles are required so mark them as such.
=> Added required asterisks where needed

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190517T183537

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190529T122422

lib/DocumentsFieldArray/DocumentsFieldArray.js
`id` is needed for integration tests
=> DFA: Add id to delete button

translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json
=> Update translation strings as of 20190609T200038

index.js, lib/EditCard/EditCard.css, lib/EditCard/EditCard.js, lib/getSASParams.js, lib/withKiwtFieldArray/withKiwtFieldArray.js
- `EditCard` now uses Stripes' `Card` component
- `getSASParams` now supports a `value` key name as well as the `cql` key name.
- `withKiwtFieldArray` has a workaround for redux-form not rerendering the component after the `handleReplaceField`.
=> Bug fixes & tweaks

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190703T132726

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190709T154346

lib/DocumentsFieldArray/FileUploaderField.js, lib/DocumentsFieldArray/tests/DocumentsFieldArray-test.js, translations/stripes-erm-components/en.json
Handles the case where the error from the response may not be _json_ (of the type _application/json_)and in that case we just display a generalized error message
=> Display appropriate error on file uploads, refs ERM-277

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190711T172340

lib/DocumentCard/DocumentCard.css, lib/DocumentCard/DocumentCard.js, lib/DocumentCard/tests/interactor.js
Pretty simple. Times like these I love using React.
=> ERM-304: Render DocumentCard using Card component

lib/DocumentsFieldArray/FileUploaderFieldView.js, translations/stripes-erm-components/en.json
=> ERM-312 FUF: Show label about max file size

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190718T220243

CHANGELOG.md, lib/OrganizationsFieldArray/EditOrganizationCard.js, lib/OrganizationsFieldArray/OrganizationsFieldArray.js, package.json, translations/stripes-erm-components/en.json
=> ERM-344 OrgsFA: Support restricting to only one role

lib/InternalContactsFieldArray/InternalContactsFieldArray.js, lib/OrganizationsFieldArray/EditOrganizationCard.js, translations/stripes-erm-components/en.json
replace placeholder for contacts and organizations role with blank
=> ERM-306: empty placeholders for create and edit agreement panes

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190807T131714

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190815T130307

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20190903T134424

CHANGELOG.md, index.js, lib/InternalContactSelection/InternalContactSelection.js, lib/InternalContactSelection/InternalContactSelectionContainer.js, lib/InternalContactSelection/InternalContactSelectionDisplay.js, lib/InternalContactSelection/index.js, lib/InternalContactSelection/readme.md, lib/InternalContactSelection/tests/InternalContactSelection-test.js, lib/InternalContactSelection/tests/interactor.js, lib/OrganizationSelection/tests/OrganizationSelection-test.js, tests/helpers/turn-off-warnings.js, tests/index.js, tests/network/config.js, tests/network/factories/contact.js, tests/network/factories/user.js, tests/network/models/contact.js, tests/network/models/user.js, tests/network/serializers/contact.js, tests/network/serializers/user.js, translations/stripes-erm-components/en.json
Similar to `OrganizationSelection` in that it's a smart component wrapping a Selection. It's done this way because we need to grab the contacts from a given path, fetch the list of full user objects based on the `user` ids stored in the contact objects, and then augment the contact objects with the user information.
=> ERM-421: Added InternalContactSelection component

lib/ViewOrganizationCard/ViewOrganizationCard.js
wrap word when column is overflown
=> wrap word when column is overflown, refs ERM-433

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/zh_CN.json
=> Update translation strings as of 20191005T202237

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20191022T162142

lib/LoadingPane/LoadingPane.js, translations/stripes-erm-components/en.json
LoadingPane now supports `defaultWidth` and `renderPaneset` props
=> LoadingPane: Added pane size/parent functionality

lib/OrganizationsFieldArray/EditOrganizationCard.js
The two ids were clashing in tests.
=> EditOrganizationCard: Update generated id

lib/DocumentsFieldArray/DocumentsFieldArray.js, lib/EditCard/EditCard.js, lib/withKiwtFieldArray/tests/withKiwtFieldArray-test.js
This is a fix for issues ERM-585 and ERM-586
=> ERM-585 and ERM-586: added hasMargin to DocumentsFieldArray.

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/he.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/ja.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20191125T160504

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/it_IT.json
=> Update translation strings as of 20191127T181804

package.json, translations/stripes-erm-components/en.json, translations/stripes-erm-components/en_US.json
=> ERM-625: Maximum file size message needs updating

lib/FileUploaderField/FileUploaderFieldView.js
https://issues.folio.org/browse/ERM-608
=> ERM-608 FileUploaderField: Add Tooltip to delete button

lib/DocumentsFieldArray/DocumentsFieldArray.js, lib/ViewOrganizationCard/ViewOrganizationCard.js
- ERM-631: ViewOrgCard: Render the whole interface name as a link, not just the icon.
- ERM-602: DFA: Support unsetting of document categories.
=> ERM-602, ERM-631: ViewOrgCard and DocsFieldArray tweaks

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/he.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/ja.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20191220T155503

translations/stripes-erm-components/es_ES.json
=> Update translation strings as of 20191223T213508

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/he.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/ja.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20200109T152437

translations/stripes-erm-components/ar.json
=> Update translation strings as of 20200110T211826

translations/stripes-erm-components/fr_FR.json
=> Update translation strings as of 20200117T173544

translations/stripes-erm-components/it_IT.json
=> Update translation strings as of 20200203T164535

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/fr_FR.json
=> Update translation strings as of 20200224T151433

lib/CustomPropertiesConfigListFieldArray/CustomPropertiesConfigListFieldArray.js, lib/CustomPropertiesConfigListFieldArray/CustomPropertyField.js, lib/CustomPropertiesConfigListFieldArray/tests/CustomPropertiesConfigListFieldArray-test.js, lib/CustomPropertiesConfigListFieldArray/tests/CustomPropertiesConfigListFieldArrayInteractor.js, translations/stripes-erm-components/en.json
This PR will add confirmation modals to deletion of custom properties, such as Supplementary Agreements and Terms in licenses.
=> ERM-730: Prompt for confirmation when deleting custom properties

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/he.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/ja.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/ur.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20200319T202257

index.js, lib/DuplicateModal/DuplicateModal.css, lib/DuplicateModal/DuplicateModal.js, lib/DuplicateModal/index.js, lib/DuplicateModal/tests/DuplicateModal-test.js, lib/DuplicateModal/tests/interactor.js, lib/errorTypes.js, translations/stripes-erm-components/en.json
- Moved the clone functionality across agreements and license into a shared component
- Tests
=> Added DuplicateModal shared component, refs ERM-814

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/he.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/ja.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/ur.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20200420T134821

translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20200519T123842

translations/stripes-erm-components/en_GB.json
=> Update translation strings as of 20200527T144757

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/he.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/ja.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/ur.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20200624T182544

lib/OrganizationsFieldArray/EditOrganizationCard.js, lib/OrganizationsFieldArray/tests/OrganizationsFieldArray-test.js, lib/OrganizationsFieldArray/tests/interactor.js, lib/ViewOrganizationCard/ViewOrganizationCard.js, lib/ViewOrganizationCard/tests/ViewOrganizationCard-test.js, lib/ViewOrganizationCard/tests/interactor.js, translations/stripes-erm-components/en.json, translations/stripes-erm-components/en_US.json
* add org note to translations
* add org note to edit card
* add note to ViewOrganizationCard
=> add note to organizations refs ERM-966, ERM-967

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/he.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/ja.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/ur.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20200701T150841

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/he.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/ja.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/ur.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20200716T140311

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/pt_BR.json
=> Update translation strings as of 20200723T031126

translations/stripes-erm-components/ru.json
=> Update translation strings as of 20200723T131158

lib/EResourceType/EResourceType.js, lib/EResourceType/tests/EResourceType-test.js, lib/EResourceType/tests/interactor.js, lib/EResourceType/tests/resources.js
* add publicationType property to EResourceType
=> ERM-943 Separate ERM 'publication type' from 'type'

translations/stripes-erm-components/ar.json, translations/stripes-erm-components/ca.json, translations/stripes-erm-components/da.json, translations/stripes-erm-components/de.json, translations/stripes-erm-components/en_GB.json, translations/stripes-erm-components/en_SE.json, translations/stripes-erm-components/en_US.json, translations/stripes-erm-components/es.json, translations/stripes-erm-components/es_419.json, translations/stripes-erm-components/es_ES.json, translations/stripes-erm-components/fr.json, translations/stripes-erm-components/fr_FR.json, translations/stripes-erm-components/he.json, translations/stripes-erm-components/hi_IN.json, translations/stripes-erm-components/hu.json, translations/stripes-erm-components/it_IT.json, translations/stripes-erm-components/ja.json, translations/stripes-erm-components/ko.json, translations/stripes-erm-components/pt_BR.json, translations/stripes-erm-components/pt_PT.json, translations/stripes-erm-components/ru.json, translations/stripes-erm-components/ur.json, translations/stripes-erm-components/zh_CN.json, translations/stripes-erm-components/zh_TW.json
=> Update translation strings as of 20200922T125348

translations/stripes-erm-components/ko.json
=> Update translation strings as of 20201026T135354

translations/stripes-erm-components/ja.json
=> Update translation strings as of 20201102T140138

translations/stripes-erm-components/ja.json
=> Update translation strings as of 20201124T212804

lib/keyboardShortcuts.js
Simply added
```
{
name: 'duplicateRecord',
shortcut: 'alt+c',
},
```
to keyboardShortcuts.js
=> STCOM-770 Add duplicateRecord shortcut

test/jest/babel.config.js
Reverts folio-org/stripes-erm-components#373
=> Revert "Add @babel/plugin-proposal-optional-chaining to babel config"

lib/OrganizationsFieldArray/EditOrganizationCard.js, lib/OrganizationsFieldArray/RolesFieldArray.js, lib/OrganizationsFieldArray/tests/OrganizationsFieldArray-test.js, lib/OrganizationsFieldArray/tests/interactor.js
=> fix OrganizationsFieldArray-test.js, refs ERM-1746

lib/FileUploaderField/FileUploaderFieldView.js
added in div to support interactor when hasDownloadPerm not present
=> ERM-1001:Separate permissions for file download in Licenses/Agreements

test/jest/__mock__/stripesCore.mock.js, test/jest/__mock__/stripesSmartComponents.mock.js
* change fakeMutators, fakeResources, add HandlerManager in stripesCore.mock
* add NotesSmartAccordion, ControlledVocab in stripesSmartComponents.mock
=> ERM-1491 Add test coverage for ui-agreements PickListSettings

lib/AlternativeNamesFieldArray/tests/AlternativeNamesFieldArray-test.js, lib/ViewOrganizationCard/tests/ViewOrganizationCard-test.js, package.json
Bumped dependency on eslint-config-stripes to 6.0.0
ERM-1971
=> chore: eslint-config-stripes

jest.config.js
Ensure stripes-kint-components, and specifically the @k-int namespace, are dealt with properly in the jest config shared by other apps
refs ERM-1906
=> test: Stripes-kint-components

.eslintrc, package.json, tests/helpers/index.js, tests/helpers/translationsProperties.js
Set up RTL environment for jest testing
ERM-2041
=> chore: RTL

test/jest/__mock__/stripesCore.mock.js, test/jest/helpers/Harness.js
Added queryClient to stripes-kint-component harness, also added useOkapiKy mock to mocks directory
=> test: React Query RTL work

lib/FormCustomProperties/CustomPropertiesListField.js, package.json
* add filter for non-primary custom properties in renderCustomPropertyName function
=> ERM-2051 primary terms are listed in drop-down for optional terms

lib/DuplicateModal/DuplicateModal.test.js
=> ERM-1320 Add test coverage for stripes-erm-components DuplicateModal

lib/LicenseCard/LicenseCard.test.js
=> ERM-1330 Add test coverage for stripes-erm-components LicenseCard

lib/InternalContactSelection/InternalContactSelection.test.js, lib/InternalContactSelection/InternalContactSelectionContainer.js, lib/InternalContactSelection/InternalContactSelectionContainer.test.js, lib/InternalContactSelection/InternalContactSelectionDisplay.test.js, lib/InternalContactSelection/testResources.js
* Add RTL tests for InternalContactSelection component
* Add RTL tests for InternalContactsSelectionContainer component
* Add data-testid to InternalContactsSelectionContainer 
* Add RTL tests for InternalContactsSelectionDisplay component
=> ERM-1328, Add test coverage for InternalContactSelection

lib/InternalContactsFieldArray/InternalContactsFieldArray.js, lib/InternalContactsFieldArray/InternalContactsFieldArray.test.js, lib/InternalContactsFieldArray/UserField.test.js, lib/InternalContactsFieldArray/testResources.js, package.json
* Add RTL test for InternalContactsFieldArray component
* Add RTL test for UserField component
=> ERM-1329, Add test coverage for InternalContactsFieldArray

lib/OrganizationSelection/OrganizationSelection.test.js, lib/OrganizationSelection/OrganizationSelectionContainer.js, lib/OrganizationSelection/OrganizationSelectionContainer.test.js, lib/OrganizationSelection/OrganizationSelectionDisplay.test.js, lib/OrganizationSelection/testResources.js
* Add RTL tests for OrganizationSelection component
* Add RTL tests for OrganizationSelectionContainer component
* Add data-testid to OrganizationSelection component
* Add RTL tests for OrganizationSelectionDisplay component
=> ERM-1334, Add test coverage for OrganizationSelection

CHANGELOG.md, package.json
Version bump and changelog section
ERM-2024
=> chore: Release 6.2.0

test/jest/__mock__/kintComponents.mock.js
Added mocks for EditableRefdataList and EditableRefdataCategoryList
ERM-2215
=> test: Mocks

lib/OrganizationsFieldArray/EditOrganizationCard.js, lib/OrganizationsFieldArray/EditOrganizationCard.test.js, lib/OrganizationsFieldArray/FieldPrimaryOrg.test.js, lib/OrganizationsFieldArray/OrganizationsFieldArray.test.js, lib/OrganizationsFieldArray/RolesFieldArray.js, lib/OrganizationsFieldArray/RolesFieldArray.test.js, lib/OrganizationsFieldArray/testResources.js
* Add RTL tests for OrganizationsFieldArray component
* Add RTL tests for EditOrganizationCard component
* Add data-testid for OrganizationsFieldArray component
* Add RTL tests for RolesFieldArray component
* Add data-testid for RolesFieldArray component
* Add RTL tests for FielPrimaryOrg component
* Add testResources file
=> ERM-1335, Add test coverage for OrganizationsFieldArray

lib/TitleOnPlatformLink/TitleOnPlatformLink.test.js, lib/ViewOrganizationCard/ViewOrganizationCard.js, lib/ViewOrganizationCard/ViewOrganizationCard.test.js, lib/ViewOrganizationCard/testResources.js
* Add RTL tests for ViewOrganizationCard component
* Add data-testid for ViewOrganizationCard component
=> ERM-1339 RTL tests for ViewOrganizationCard component

lib/Tags/Tags.test.js, package.json
Added dev dep for babel preset-env, which we use in our babel config
=> build: Added dev dep

package.json
I don't know what I'm doing (clearly)
=> build: Removed peer deps again (sorry)

.eslintrc
=> build: Breaking eslintrc change

CHANGELOG.md, lib/hooks/useBatchedFetch.js, package.json
useBatchedFetch change (Cherry pick not an option due to combination with some devDep changes... my bad)
ERM-2301
=> chore: Release 2.6.1

CHANGELOG.md
=> docs: Added changelog section from 6.2.1 patch release

index.js, lib/InfoBox/InfoBox.css, lib/InfoBox/InfoBox.js, lib/InfoBox/index.js, lib/NewBox/NewBox.js, lib/NewBox/index.js, translations/stripes-erm-components/en.json
Added InfoBox component for small "badge" type box with bold white text, also NewBox using that to set up a standardised "NEW" badge
refs ERM-2313
=> feat: InfoBox/NewBox

test/jest/helpers/TestForm.js
Tweaked testForm so that it can be used with other mutators
refs ERM-2313
=> test: TestForm

lib/DateFilter/DateFilter.js
Added closedByDefault prop to DateFitler component
=> feat: DateFilter props

lib/SearchKeyControl/SearchKeyControl.css, lib/SearchKeyControl/SearchKeyControl.js
style: SearchKeyControl
Changed rendering of SearchKeyControl options to be full responsive
ERM-2342
=> ERM-2342: Responsive behaviour of Agreement search field selections

lib/SearchKeyControl/SearchKeyControl.css
Added margin here, removed padding there...
ERM-2342
=> style: CSS tweaks

CHANGELOG.md, package.json
Bumped version number to 7.0.0 and updated CHANGELOG
ERM-2239
=> chore: Release 7.0.0

CHANGELOG.md, package.json
Added changelog section and bumped version
ERM-2239
=> chore: Post Release

lib/hooks/useAgreement.js
Added queryParams prop to useAgreement hook
ERM-2243
=> feat: useAgreement

lib/FormattedDateTime/FormattedDateTime.js
Added id to FormattedDateTime to allow for interactor based testing
ERM-2463
=> feat: FormattedDateTime

lib/hooks/useFileHandlers.js
feat: useFileHandlers
Make use of downloadBlob also in useFileHandlers
ERM-2467
=> ERM-2467: Change export file name and file extension in Agreements and Local KB admin

package.json
Forgot to do peeer dep as well... doh!
refs ERM-2589, ERM-2596
=> build: Stripes

lib/OrganizationSelection/OrganizationSelection.js
Small tweaks to help console errors
=> chore: Pre release linting

index.js, lib/recursiveUrlDecoding.js
* create recursiveUrlDecoding function
=> SI-24 Avoid double encoding of user entered URLs in simple search widget

lib/DocumentsFieldArray/DocumentField.js, translations/stripes-erm-components/en.json
* add size validation to DocumentField
* add translation
=> ERM-2961 Extend length of document URL to 2048 chars

lib/SerialCoverage/SerialCoverage.js
fix: Small visual change
Small tweak to translation to neaten up render of volume/issue
ERM-2978
=> ERM-2978: Edition, volume, issue render on new line

lib/OrganizationsFieldArray/RolesFieldArray.js, lib/hooks/index.js, lib/hooks/usePrevious.js
=> feat: usePrevious

package.json
build: Bumped react peer-dep
react peer-dep now on ^18
ERM-2989
=> ERM-2989: Upgrade stripes-erm-components React to v18

lib/utils/getIdsFromUrl.js, lib/utils/index.js
Added new utility function to parse our Ids from URL
refs SI-4
=> feat: getIdsFromUrl

lib/OrganizationsArrayDisplay/OrganizationsArrayDisplay.js
* render comma conditionally
* add index, key prop
=> ERM-3126 Misleading tailing comma in OrganizationsArrayDisplay

CHANGELOG.md
=> ERM-3101 stripes-erm-components release

CHANGELOG.md, lib/utils/downloadBlob.js, package.json
Added Changelog section and bumped version number to 9.2.1
ERM-3447
=> Release 9.2.1

CHANGELOG.md
Added changelog section for 9.2.1 release
ERM-3447
=> chore: Post release 9.2.1

CHANGELOG.md
Updated CHANGELOG.md section to reflect release changes
ERM-3407
=> chore: Release 10.0.0

CHANGELOG.md, package.json
Bumped version to 10.1.0 and added new CHANGELOG.md section
=> chore: Post release 10.0.0
