- lib/CreateOrganizationModal/CreateOrganizationModalContainer.js
- lib/OrganizationSelection/OrganizationSelectionContainer.js
- lib/OrganizationSelection/OrganizationSelectionDisplay.js
- package.json
Changes focused on improving usage of components for automated testing:
- Create `id`s for `CreateOrganizationModal` elements.
- Pass `id`s through for `OrganizationSelection`
- Bump to v1.0.3 to allow users to target these changes.
> Improve testability of Organization components

- CHANGELOG.md
- index.js
- lib/DocumentsFieldArray/DocumentsFieldArray.js
- lib/LicenseCard/LicenseCard.js
- lib/LicenseCard/index.js
- lib/LicenseCard/readme.md
- package.json
- translations/stripes-erm-components/en.json
Renders a card displaying information about licenses of the type [`License`](https://github.com/folio-org/mod-licenses/blob/master/service/grails-app/domain/org/olf/licenses/License.groovy) implemented by the `licenses` Okapi interface.
Simply passing a license object is all that's required.
```
import { LicenseCard } from '@folio/stripes-erm-components';
...
return <LicenseCard license={license} />;
```
| Name | Type | Description | Required | Default |
--- | --- | --- | --- | --- |
| `className` | string |
| `license` | object | [`License`](https://github.com/folio-org/mod-licenses/blob/master/service/grails-app/domain/org/olf/licenses/License.groovy) | Yes |
| `renderName` | bool | Set to `false` to turn off rendering the license name  | | `true` |
> Added LicenseCard component

- CHANGELOG.md
- index.js
- lib/DocumentCard/DocumentCard.js
- lib/LicenseCard/LicenseCard.js
- lib/LicenseEndDate/LicenseEndDate.js
- lib/LicenseEndDate/index.js
- lib/LicenseEndDate/readme.md
- package.json
Renders the effective end date of a license. This can differ due to fields such as `openEnded`.
Simply passing a license object is all that's required.
```
return <LicenseEndDate license={license} />;
```
| Name | Type | Description | Required | Default |
--- | --- | --- | --- | --- |
| `license` | object | [`License`](https://github.com/folio-org/mod-licenses/blob/master/service/grails-app/domain/org/olf/licenses/License.groovy) | Yes |
> Added LicenseEndDate component

- lib/getSASParams.js
I need this so that when the user chooses to search in an index other than the default one specified as `searchKey` at compile-time, that selection can be overridden by the `qindex` portion of the URL query.
> Add support for qindex

- lib/getSASParams.js
This is that other small change I mentioned in Slack.
If the value that you pass at compile-time as `searchKey` or at run-time as `quindex` contains commas, then that compound value is split into multiple atomic values each of which gives rise to its own `match` parameter. So when at a URL containing `qindex=name,tags.value,symbols.symbol`, the generated back-end URL will include `?match=name&match=tags.value&match=symbols.symbol`.
> Support comma-separated multiple `match` parameters

- CHANGELOG.md
- index.js
- lib/DocumentsFieldArray/DocumentsFieldArray.js
- lib/withKiwtFieldArray/index.js
- lib/withKiwtFieldArray/readme.md
- lib/withKiwtFieldArray/withKiwtFieldArray.js
- package.json
A higher-order component to simplify the interface between redux-form `<FieldArray>` and arrays in a backend module that uses the [K-Int Web Toolkit](https://github.com/k-int/web-toolkit-ce/) to manage its arrays via the [ExtendedWebDataBinder](https://github.com/k-int/web-toolkit-ce/blob/master/src/main/groovy/com/k_int/web/toolkit/databinding/ExtendedWebDataBinder.groovy).
See added readme for more info.
> Added withKiwtFieldArray HOC

- .gitignore
- CHANGELOG.md
- lib/DocumentCard/DocumentCard.js
- lib/DocumentsFieldArray/DocumentsFieldArray.js
- package.json
- translations/stripes-erm-components/en.json
* modify DocumentCard and DocumentFieldArray components to support supplementary information with document categories
* add minor version 1.3.1 to CHANGELOG.md and package.json
* add doc.category to en.json
* add .DS_Store to .gitignore
> ERM-79: set supplementary information for a license

- CHANGELOG.md
- lib/DocumentsFieldArray/DocumentsFieldArray.js
- lib/getSASParams.js
- package.json
`queryGetter` allows consuming modules to store their query string params in a resource _other_ than `query`. 
This is very useful for plugins.
> getSASParams: Add `queryGetter` option

- CHANGELOG.md
- package.json
- Tested with sample "Hello World" UI app. No difference in bundle size but this will shake future unused code blocks.
> turned off sideEffects to enable tree-shaking

- CHANGELOG.md
- index.js
- lib/InternalContactsFieldArray/InternalContactsFieldArray.js
- lib/InternalContactsFieldArray/UserPicker.js
- lib/InternalContactsFieldArray/index.js
- lib/InternalContactsFieldArray/readme.md
- lib/InternalContactsFieldArray/tests/InternalContactsFieldArray-test.js
- lib/InternalContactsFieldArray/tests/interactor.js
- lib/validators.js
- package.json
- translations/stripes-erm-components/en.json
Generalized the existing internal contacts editing components in ui-agreements and cleaned them up a bit.
A subsequent PR to switch over to this in ui-agreements is upcoming first, and then I'll add the ability to manage internal contacts for ui-licenses.
> ERM-179: Added InternalContactsFieldArray component

- CHANGELOG.md
- index.js
- lib/Card/Card.css
- lib/Card/Card.js
- lib/Card/index.js
- lib/Card/readme.md
- lib/Card/tests/Card-test.js
- lib/Card/tests/interactor.js
Added a basic `Card` component to let us render the card-based layouts we're about to start using often in ERM apps. This was inspired by the address edit UI in the Users app and picked up by our UX designer after consultation with Filip.
**Basic Usage**
**In The Wild**
Eventually, I believe this is a candidate for being in @folio-org/stripes itself.
> ERM-230: Added Card Component

- lib/DocumentsFieldArray/DocumentsFieldArray.js
- lib/DocumentsFieldArray/FileUploaderFieldView.js
- lib/DocumentsFieldArray/tests/DocumentsFieldArray-test.js
- Hide document category selector when the array is empty as well as undefined.
- Tweak proptypes for file modified timestamp.
- Default rendering tests
> DFA: Hide document categories when empty

- lib/DocumentsFieldArray/DocumentsFieldArray.js
- lib/DocumentsFieldArray/FileUploaderField.js
- lib/DocumentsFieldArray/readme.md
- lib/DocumentsFieldArray/tests/DocumentsFieldArray-test.js
Previously we preemptively and explicitly deleted files using the `onDeleteFile` callback. We've changed the behaviour on the backend as on https://github.com/folio-org/mod-licenses/pull/88 so we're now removing `onDeleteFile` from the API and just marking the `fileUpload` param as `null` when it the delete button is pressed.
> FUF: Mark files for deletion on submit

- lib/DocumentsFieldArray/FileUploaderField.js
- lib/Tags/Tags.js
`DocumentsFieldArray` sets each indice's component row with a `key` of the index into the array.
When we have two documents and we delete the first one, the second document "slides up" and during the next render, the components used to render it will have the same key as the components that were used for the first component.  As a result, React will _reuse_ those components directly because of this. 
However, `FileUploadField` stores any uploaded file's information in its internal `state`, which will persist if a component is reused. As a result, that second component that "slid up"? It now inherits the first component's `state`.
To test this, add two documents, upload a file to the first, and then delete it. Note that the second document (now the only one), displays the information about …
> FUF bug fix & Tags cleanup

- CHANGELOG.md
- lib/getSASParams.js
- package.json
This allows client code to decide dynamically how to massage the query based on any prop. Requires a recent stripes-connect (^5.2.3)
> getSASParams passes props into queryGetter

- lib/LicenseCard/LicenseCard.js
- lib/LicenseCard/tests/LicenseCard-test.js
- lib/ViewOrganizationCard/ViewOrganizationCard.js
- package.json
- LicenseCard should render a link to the license record
- Organization's Interface external links should open in a new tab
> ERM-319 ERM-320: Link tweaks to License and Organization cards

- .eslintrc
- CHANGELOG.md
- package.json
Removed `devDependencies` on stripes-components and stripes-core.
> Release 1.5.4

- CHANGELOG.md
- index.js
- lib/InternalContactCard/InternalContactCard.js
- lib/InternalContactCard/index.js
- lib/InternalContactCard/tests/InternalContactCard-test.js
- lib/InternalContactCard/tests/interactor.js
Pretty simple. Basically just renders an internal contact as a Card. Tried to be as flexible as possible with the props coming in and not assume that the currently-required fields are always going to be required.
> ERM-309: Added InternalContactCard component

- CHANGELOG.md
- lib/DocumentsFieldArray/DocumentsFieldArray.js
- package.json
This seemed weird at first because the flexbox should automatically keep the div at the same height as its sibling to the left. But the extra Row/Col trashes that flexbox behaviour. Removed the extra Row/Col since it doesn't even do anything.
> ERM-295: Fixed DFA dropzone resizing

- CHANGELOG.md
- lib/FileUploaderField/FileUploaderFieldView.js
Added styling to force line breaks everywhere in the filename, not just at hyphens and whitespace.
> ERM-432: Fixed filename line breaks

- CHANGELOG.md
- lib/InternalContactsFieldArray/UserField.js
- package.json
`touched` really shouldn't be what we're checking anymore since it remains `false` due to the lack on a `blur` event. `dirty` works better now.
> Release 1.7.1

- tests/helpers/turn-off-warnings.js
> Turn off React Intl errors in BigTest

- lib/DocumentsFieldArray/DocumentsFieldArray.js
[ERM-564](https://issues.folio.org/browse/ERM-564)
Backends written in Groovy do not interpret an undefined value as being an "unsetting" of a field. Eg, if a given record has `{ id: 1, foo: "bar", bar: "baz" }` and I PUT `{ id: 1, foo: "aubergine" }`, then the record will now have `{ id: 1, foo: "aubergine", bar: "baz" }`.
This is a problem for us because [React Final Form coalesces empty strings into undefineds](https://final-form.org/docs/final-form/faq#why-does-final-form-set-my--field-value-to-undefined). To work around this, we use [the docs' suggested `parse` hack](https://final-form.org/docs/react-final-form/types/FieldProps#parse).
> ERM-564: Support unsetting of optional fields

- lib/FileUploader/FileUploader.js
- lib/FileUploaderField/FileUploaderField.js
- lib/FileUploaderField/FileUploaderFieldView.js
- [stripes-final-form uses final-form-focus to automatically focus the first form element that has an error](https://github.com/folio-org/stripes-final-form/blob/master/lib/StripesFinalFormWrapper.js#L5)
- [final-form-focus finds form elements using this algorithm](https://github.com/final-form/final-form-focus/blob/master/src/findInput.js#L9)
- So we need to set `name` on the form element we want to be autofocused. 
- We set it on the button since it's the most visible and most obvious for this rask.
> FileUploader: Apply `name` attribute to <button>

- lib/ViewOrganizationCard/ViewOrganizationCard.js
- translations/stripes-erm-components/en.json
This is a little bit of work to change the way that the name of an organization is rendered on an organization card.
I've had some problems getting my agreements form to work, so I've been unable to test whether all tests pass on ui-agreements, but there seem to be no issues in stripes-erm-components or ui-licenses using this, at least for me locally.
> ERM-603 and ERM-604: PR to change the way organization cards are rendered

- lib/DocumentsFieldArray/DocumentsFieldArray.js
The `true` case in the ternary expression was still firing when the first operand of the `||` was false. This shouldn't happen, we need the OR to short-circuit to `true`, so I added parens to make this explicit.
This handles ERM-669 in a more generic way since it maintains supported for the deprecated `deleteButtonTooltipText` prop
> DFA: fixed logic with parens

- lib/CustomPropertiesList/CustomPropertiesList.js
- lib/CustomPropertiesList/tests/CustomPropertiesList-test.js
- tests/helpers/Harness.js
- tests/helpers/setupApplication.js
Use `FormattedNumber` to display numbers in the FOLIO locale
With this PR, if the browsers locale is set to `German`... inputs like `16,3` entered in the form are displayed as `16,3` in the view pane if the FOLIO locale is set to `German` and displayed as `16.3` if the locale is set to `English`
> Use <FormatedNumber /> for displaying numbers, fixes ERM-747

- lib/CreateOrganizationModal/CreateOrganizationModal.js
- lib/CreateOrganizationModal/tests/CreateOrganizationModal-test.js
- lib/FileUploader/FileUploader.js
- lib/FileUploaderField/FileUploaderField.js
- lib/FileUploaderField/FileUploaderFieldView.js
- lib/withKiwtFieldArray/tests/withKiwtFieldArray-test.js
Rather than letting the upload happen and allowing the backend to throw a 500 error upon receiving the 201st MB, we can set the `maxSize` on React Dropzone and reject the file at the start.
Also, was debugging a bunch of test failures that mostly ended up being because of [multiple copies of stripes-components](https://folio-project.slack.com/archives/C210UCHQ9/p1585916884128500). 🤦‍♂ 
- That ended up with me realising that we should just deprecate CreateOrganizationModal and skip its tests til then.
- Also realised we need to apply the ERM-825 workaround in the wKFA tests to get them to pass.
> ERM-809: Prevent upload of files greater than 200MB

- index.js
- lib/CreateOrganizationModal/CreateOrganizationModal.js
- lib/preventResourceRefresh.js
This function takes in a map of the resource and corresponding array of actionTypes and returns a false if the resource thats executing the refresh needs to be prevented from refreshing
Eg: Assume you dont want to refresh the agreementLine resource because the agreement containing it has been deleted, you could just pass a 
`shouldRefresh: preventResourceRefresh({ 'agreement': ['DELETE'] })`
option to it and that would prevent it from refreshing
> Add preventResourceRefresh utility function, refs ERM-852

- lib/Tags/Tags.js
A record can be deleted via a mutator, which
then triggers a refetch of `entities` that then
generates a 404/500.
> Tags: Don't throw errors

- lib/ViewOrganizationCard/ViewOrganizationCard.js
Languages like German need this space, currently the right part
of the button and of the button label are out of the visible area
for German ("Anmeldeinformation anzeigen").
> Increase size of credentials show hide button from 160px to 300px

- lib/OrganizationsFieldArray/EditOrganizationCard.js
- lib/OrganizationsFieldArray/OrganizationsFieldArray.js
- lib/OrganizationsFieldArray/RolesFieldArray.js
- lib/OrganizationsFieldArray/tests/OrganizationsFieldArray-test.js
Refactored component to functional
Tweaked form submission to use `id` instead of `value`
Fixed hungry focus bug (When no Org selected, entering details in other fields would be cut off by focus returning to link button)
> ERM-1749: On updating an existing organisation role the role value is updated but not the role label

- lib/InternalContactSelection/InternalContactSelectionDisplay.js
- lib/OrganizationSelection/OrganizationSelectionDisplay.js
In both cases, the problem is that due to recent changes in how translations are handled, the translation passed to the render-function content of `<FormattedMessage>` can sometimes be an array of a single string, rather than just a string. We allow for this case by checking the type of passed translation.
> Fix two prop-types errors

- lib/Tags/Tags.js
Tag fetch for erm-components wouldn't fire after an eholdings tags fetch for a different shape, causing problems when attempting to tag an agreement line for an eholdings resource directly after assigning that resource. Added a dataKey to our Tag fetch to ensure unique fetch for our usage
refs ERM-2065
> fix: Tag fetching

- lib/hooks/useBatchedFetch.js
Allow useBatchedFetch to accept a nsArray prop to use in place of the namespace array default it provides. This allows us to choose a convention as we call the hook.
ERM-2225, ERM-2227
> feat: useBatchedFetch Namespacing

- lib/DocumentCard/DocumentCard.js
- lib/DocumentCard/DocumentCard.test.js
feat: DocumentCard hideCategory
Added hideCategory prop to DocumentCard to enable implementors to hide that keyValue. Tests amended and linting
ERM-2366
> ERM-2366: Core documents for a License shouldn't display a category

- CHANGELOG.md
- package.json
Reverts folio-org/stripes-erm-components#563. PR #563 solved a small problem by removing some test-related dependencies which have unsatisfied peer-dep warnings when built at the platform-level, but doing that created a much worse problem that actually resulted in a build failure at the platform level because some public test infrastructure relied on those dependencies. 
It's no good having a noisy platform build, but a having a broken platform build is (of course) even worse. And since treeshaking is doing its job for us and keeping those test-related deps out of the final bundle, it's clear the prudent thing is to just go back to how things were pre-563 and publish yet another patch release. 
Sorry for the churn.
> Revert "ERM-2395: Remove @folio/stripes-testing as direct dependency of stripes-erm-components"

- CHANGELOG.md
- package.json
- Refs https://issues.folio.org/browse/ERM-2616.
- Upgrade will be happening across all of Stripes framework and modules that reference react-redux.
- v7 to v8 is a very harmless upgrade and is only considered breaking since they removed a few rarely used functions (which I confirmed we don't use). See https://github.com/reduxjs/react-redux/releases/tag/v8.0.0 for more details.
> ERM-2616 Upgrade react-redux to v8

- lib/hooks/useUsers.js
fix: users request
User details were not being correctly fetched due to an error in the joining logic between ids in the request. This has been rectified
ERM-2547
> ERM-2547: On agreement and license user details do not display when more than one user linked to agreement/license as Internal contact

- lib/LogsList/LogsList.js
- translations/stripes-erm-components/en.json
feat: LogInfo title
Added title MDC display to LogsList so that when title data is available it can be seen clearly in the frontend
ERM-2474
> ERM-2474: Local KB admin: Info log export populates title element in additionalInfo with non-relevant data

- lib/InternalContactSelection/InternalContactSelection.js
- lib/hooks/useBatchedFetch.js
fix: ERM-2929
Syntax error in useBatchedFetch grabbing final array element using [-1] instead of .at(-1)
Also ensure unique sort order for those contacts
ERM-2929
> ERM-2929: InternalContactSelection gets stuck in fetch loop

- lib/InternalContactSelection/InternalContactSelection.js
Dedupe contacts by user before fetching related users, just as the contact list is deduped by user when iterating through it inside `useEffect`. Without this change in place, the JS console fills with warnings:
```
Warning: Maximum update depth exceeded. This can happen when a
component calls setState inside useEffect, but useEffect either
doesn't have a dependency array, or one of the dependencies
changes on every render.
at InternalContactSelection.js:49
```
TBH, I don't entirely understand why this fix works, but it allows the `users` value to stabilize, thus preventing the dependencies from changing on every render.
Refs [ERM-2929](https://issues.folio.org/browse/ERM-2929)
> ERM-2929 dedupe contacts by user before iterating

- lib/hooks/useChunkedCQLFetch.js
- lib/hooks/useChunkedUsers.js
feat: useChunkedCQLFetch imrpovements
Improvements to useChunkedCQLFetch to hopefully allow it to be used generically across ERM. If it satisfies all our use cases then it is ready to be moved to stripes-core
Improvements:
- Built in id list deduplication
- Swap to slightly more efficient (lengthwise) id query
- Ability to pass in queryOptions to useQueries
- Ability to tweak CONCURRENT_REQUESTS and STEP_SIZE
- These have been left in the form of constants to discourage that
refs STCOR-730, ERM-2967
> ERM-2967: Use useChunkedCQLFetch consistently across ERM

- CHANGELOG.md
- lib/hooks/index.js
- lib/hooks/useChunkedCQLFetch.js
- lib/hooks/useChunkedUsers.js
- lib/hooks/useParallelBatchFetch.js
Created new hook "useParallelBatchFetch" which brings batch fetching from KIWT endpoints in line with useChunkedCQLFetch, in that multiple fetches happen in parallel, speeding the process up significantly.
Also tweaks to useChunkedCQLFetch to bring it in line with PR in stripes core
> feat: useParallelBatchFetch

- CHANGELOG.md
- lib/InternalContactSelection/InternalContactSelection.js
- lib/hooks/useBatchedFetch.js
- lib/hooks/useParallelBatchFetch.js
- lib/hooks/useUsers.js
feat: Swap to useParallelBatchFetch
Swap InternalContactSelection over to use useParallelBatchFetch in place of useBatchedFetch for internal contacts fetch
Also pass total from useParallelBatchFetch
Deprecated useUsers and useBatchedFetch
refs ERM-2973, ERM-2974, ERM-2975, ERM-2976
> ERM-2973: Replace naive fetch hooks with parallelised ones (and deprecate)

- lib/hooks/useParallelBatchFetch.js
Fixed bug where a parallel batch fetch which only needs a single page would remain in a "loading" state forever and hence not return the items
refs ERM-2973
> fix: Parallel batch fetch single page never returns items

- lib/hooks/usePrevNextPagination.js
chore: Remove case
Remove submit.all case from page reset to avoid page reset on first load
> ERM-2937: usePrevNextPagination

- lib/InfoBox/InfoBox.js
- lib/NewBox/NewBox.css
- lib/NewBox/NewBox.js
InfoBox/NewBox now accept a className prop, in which you can add additional css information. NewBox makes use of this by default.
ERM-3040
> feat: InfoBox className

- CHANGELOG.md
- lib/hooks/usePrevNextPagination.js
Occasionally usePrevNextPagination would attempt a numeric operation on an undefined variable `currentPage`. This is now protected against.
> fix: usePrevNextPagination null safety

- CHANGELOG.md
- package.json
> chore: Release 9.1.0

- package.json
Bump version of formatjs/cli to ensure we're bringing in the same version across our modules
> build: @formatjs/cli
